spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop-service/**
          filters:
            - RewritePath=/shop-service/(?<segment>.*), /$\{segment}

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - RewritePath=/customer-service/(?<segment>.*), /$\{segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}

        - id: log-service
          uri: http://elasticsearch:9200
          predicates:
            - Path=/log-service/**
          filters:
            - RewritePath=/log-service/(?<segment>.*), /$\{segment}