server:
  port: 8081

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0

rabbitmq:
  default:
    exchange: orderShopTopicExchange
    fanout-exchange: orderShopFanoutExchange
  queues:
    outbound:
      orderCreatedQueue:
        name: order_created_queue
      customerVerificationQueue:
        name: customer_verification_queue
      creditCardAuthorizationQueue:
        name: credit_card_authorization_queue
        routing-key: credit_card_authorization_queue
      orderVerifiedQueue:
        name: order_verified_queue
        routing-key: order_verified_queue
    inbound:
      shopCatalogVerifiedQueue: shop_catalog_verified_queue
      customerVerifiedQueue: customer_verified_queue
      creditCardAuthorizedQueue: credit_card_authorized_queue
      orderPreparedQueue: order_prepared_queue